[package]
name = "basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jewelry = { git = "https://github.com/tuna2134/jewelry.git" }
tokio = "*"
